ALTER TABLE ai_reviews ADD COLUMN repository_full_name TEXT NOT NULL DEFAULT '';
ALTER TABLE ai_reviews ADD COLUMN turns INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_reviews ADD COLUMN files_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_reviews ADD COLUMN input_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_reviews ADD COLUMN output_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_reviews ADD COLUMN duration_ms INTEGER NOT NULL DEFAULT 0;
